config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>" class="card" style="width: 25rem;">
  <div class="card-header">
    <h2>
      <%= flat.name %>
    </h2>

    <p>
      <strong><%= flat.address %></strong>
    </p>

    <i class="fa-solid fa-users"></i><%=flat.number_of_guests %>

    <i class="fa-solid fa-euro-sign"></i><%= flat.price_per_night %>

  </div>

  <div class="card-body">
      <%= link_to "More info", flat, class:"link-no-underline" %>
  </div>
</div>

app/views/flats/_form.html.erb
<div class=justify-content-md-center>
  <%= simple_form_for(@flat) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class:"btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/flats/_navbar.html.erb
<div class="container modal-fullscreen">
  <div class="row justify-content-md-center pt-2 pt-2 background-grey">
    <div class="col col-lg-3">
      <h4>Simple Airbnb</h4>
    </div>
    <div class="col-md-auto">
    </div>
    <div class="col col-lg-2">
      <button type="button" class="btn btn-outline-primary"><%= link_to "New flat", new_flat_path, class:"link-no-underline" %></button>
    </div>
  </div>
</div>

app/views/flats/edit.html.erb
<div style="width: 50rem;">

<h1>Editing flat</h1>

<%= render "form", flat: @flat %>

</div>

<br>

<div class="card-body d-grid gap-2 d-md-flex justify-content-center" >
  <%= link_to "Show this flat", @flat, class:"btn btn-dark" %>
  <%= link_to "Back to flats", flats_path, class:"btn btn-dark"%>
</div>

app/views/flats/index.html.erb
<h1>All our Flat (<%= @flats.count %>)</h1>

<div id="flats" class="card-grid">
  <% @flats.each do |flat| %>
    <%= render flat %>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path, class:"btn btn-black" %>
</div>

app/views/flats/show.html.erb
<div id="<%= dom_id @flat %>" style="width: 50rem;">

  <div class="card-header mt-4 mb-4">
    <h1><%= @flat.name %></h1>
    <p><strong><%= @flat.address %></strong></p>
  </div>

  <div class="card-header mb-4">
    <h3>A bit more about this flat...</h3>
    <p><strong><%= @flat.description %></strong></p>
  </div>

  <div class="card-header mb-4">
    <h3>Details</h3>
    <i class="fa-solid fa-users"></i><%=@flat.number_of_guests %>
    <i class="fa-solid fa-euro-sign"></i><%= @flat.price_per_night %>
  </div>

  <div class="card-body d-grid gap-2 d-md-flex justify-content-center" >
    <%= link_to "Back to flats", flats_path, class:"btn btn-primary" %>
    <%= link_to "Edit this flat", edit_flat_path(@flat), class:"btn btn-warning" %>
    <%= button_to "Destroy this flat", @flat, method: :delete, class:"btn btn-danger" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <%= render "flats/navbar" %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>